name = "georges-tracker-api"
main = "worker.js"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"
database_name = "georges_tracker_db"
database_id = "986bc8c8-e1c0-4f32-8362-dadb2c715e2a"
